"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['py-Image.py']
DATA_FILES = ['dnd.png']
OPTIONS = {'iconfile': '/Users/bryan-plaid/repos/py-images/ir.icns'}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
